import React,{useEffect,useRef,useState} from "react";
import {createRoot} from "react-dom/client";
import {Canvas,useFrame} from "@react-three/fiber";
import {OrbitControls,Float,Html} from "@react-three/drei";
import {motion} from "framer-motion";
import {Activity,AlertTriangle,CheckCircle2,CircleDot,Database,GitBranch,Github,LockKeyhole,Play,Radio,Shield,Terminal,TestTube2,UserCheck,XCircle,Zap} from "lucide-react";
import "./styles.css";
const API=import.meta.env.VITE_API_URL||"http://localhost:8000";
const NODES=[{id:"github",label:"GITHUB",sub:"REPOSITORY",p:[-3.6,1.5,0]},{id:"logs",label:"LOGS",sub:"OBSERVABILITY",p:[3.6,1.5,0]},{id:"db",label:"DATABASE",sub:"READ ONLY",p:[-3.8,-1.2,0]},{id:"security",label:"SECURITY",sub:"POLICY FIREWALL",p:[3.8,-1.2,0]},{id:"engineer",label:"ENGINEER",sub:"PATCH AGENT",p:[0,-2.4,0]},{id:"tester",label:"TESTER",sub:"VALIDATION",p:[0,2.35,0]}];
function Core(){const r=useRef();useFrame((_,d)=>{if(r.current)r.current.rotation.y+=d*.18});return <group ref={r}><mesh><icosahedronGeometry args={[1.15,2]}/><meshStandardMaterial wireframe emissive="#59e1ff" emissiveIntensity={2} color="#0b1730"/></mesh><mesh scale={.72}><icosahedronGeometry args={[1,1]}/><meshStandardMaterial emissive="#7c5cff" emissiveIntensity={2.8} color="#142052"/></mesh><Html center distanceFactor={8}><div className="core-label"><strong>NEXUS</strong><span>ORCHESTRATOR</span></div></Html></group>}
function Node({n,active}){return <Float speed={1.3} rotationIntensity={.12} floatIntensity={.25}><group position={n.p}><mesh><sphereGeometry args={[.34,24,24]}/><meshStandardMaterial emissive={active?"#62f6c7":"#3286ff"} emissiveIntensity={active?2.5:1.2} color="#091224"/></mesh><Html center distanceFactor={7}><div className={`node-label ${active?"active":""}`}><b>{n.label}</b><span>{n.sub}</span></div></Html></group></Float>}
function Scene({active}){return <Canvas camera={{position:[0,0,9],fov:48}}><ambientLight intensity={.45}/><pointLight position={[0,2,5]} intensity={12} color="#5de5ff"/><pointLight position={[-4,-2,2]} intensity={8} color="#806cff"/><Core/>{NODES.map(n=><Node key={n.id} n={n} active={active}/>) }<OrbitControls enableZoom={false} enablePan={false} autoRotate autoRotateSpeed={.22}/></Canvas>}
function Panel({title,icon,children,wide=false}){return <div className={`panel ${wide?"wide":""}`}><div className="panel-head"><span>{icon}{title}</span><small>LIVE</small></div>{children}</div>}
function Empty({text}){return <div className="empty"><CircleDot size={18}/>{text}</div>}
function App(){const[run,setRun]=useState(null),[events,setEvents]=useState([]),[evidence,setEvidence]=useState([]),[view,setView]=useState("command"),[busy,setBusy]=useState(false),[note,setNote]=useState("");
 const refresh=async id=>{const [r,t,e]=await Promise.all([fetch(`${API}/api/runs/${id}`).then(x=>x.json()),fetch(`${API}/api/runs/${id}/timeline`).then(x=>x.json()),fetch(`${API}/api/runs/${id}/evidence`).then(x=>x.json())]);setRun(r);setEvents(t);setEvidence(e)};
 const start=async()=>{setBusy(true);const r=await fetch(`${API}/api/runs`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({task:"Investigate why checkout is returning HTTP 500 after yesterday's deployment and fix it if safe."})}).then(x=>x.json());setRun(r);setEvents([]);setEvidence([]);setBusy(false);const ws=new WebSocket(API.replace(/^http/,"ws")+`/api/runs/${r.id}/stream`);ws.onmessage=async m=>{const e=JSON.parse(m.data);if(e.type!=="mission_state"){setEvents(x=>[...x,e]);await refresh(r.id)}}};
 const decide=async type=>{await fetch(`${API}/api/runs/${run.id}/${type}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({note})});await refresh(run.id)};
 const active=!!run,waiting=run?.status==="awaiting_approval";
 return <div className="app"><header className="topbar"><div className="brand"><div className="brand-mark">N</div><div><b>NEXUS</b><span>AUTONOMOUS ENGINEERING OS</span></div></div><div className="top-status"><span className="pulse"/>CONTROL PLANE ONLINE <i>v0.1</i></div></header><main>
 <section className="hero"><div className="hero-copy"><div className="eyebrow"><Radio size={13}/> MISSION CONTROL</div><h1>Ship software.<br/><em>With evidence.</em></h1><p>NEXUS investigates engineering incidents, proposes safe repairs, validates them, and stops before risky production actions.</p><div className="mission-input"><span>›</span><input value="Investigate checkout HTTP 500 and fix it if safe" readOnly/><button onClick={start} disabled={busy||waiting||run?.status==="running"}><Play size={15}/>{busy?"STARTING":active?"MISSION ACTIVE":"RUN MISSION"}</button></div><div className="trust-row"><span><Shield size={13}/> POLICY BOUND</span><span><LockKeyhole size={13}/> SANDBOXED</span><span><UserCheck size={13}/> HUMAN GATE</span></div></div><div className="scene"><Scene active={active}/><div className="scene-grid"/></div></section>
 <section className="mission-bar"><div><span className="label">MISSION</span><strong>{run?.id||"NX—READY"}</strong></div><div><span className="label">PHASE</span><strong>{(run?.phase||"Idle").toUpperCase()}</strong></div><div><span className="label">CONFIDENCE</span><strong>{run?.confidence||0}%</strong></div><div><span className="label">RISK</span><strong className={run?.risk==="MEDIUM"?"warn":""}>{run?.risk||"LOW"}</strong></div><div className="progress"><span style={{width:`${run?.progress||0}%`}}/></div></section>
 <nav className="tabs">{[["command","Command Center"],["timeline","Live Timeline"],["evidence","Evidence Graph"],["diff","Code Diff"],["security","Security & Policy"]].map(([id,label])=><button key={id} className={view===id?"selected":""} onClick={()=>setView(id)}>{label}</button>)}</nav>
 <section className="content">{view==="command"&&<Command run={run} evidence={evidence} waiting={waiting} note={note} setNote={setNote} decide={decide}/>} {view==="timeline"&&<Timeline events={events}/>} {view==="evidence"&&<Evidence evidence={evidence}/>} {view==="diff"&&<Diff run={run}/>} {view==="security"&&<Security run={run}/>}</section>
 </main></div>}
function Command({run,evidence,waiting,note,setNote,decide}){return <div className="grid"><Panel title="MISSION STATE" icon={<Activity size={16}/>}><div className="state-ring"><div><b>{run?.progress||0}%</b><span>MISSION</span></div></div><div className="state-text"><b>{run?.phase||"Awaiting mission"}</b><span>{run?.root_cause||"Launch the flagship checkout incident to see NEXUS operate."}</span></div></Panel><Panel title="ROOT-CAUSE SIGNAL" icon={<Zap size={16}/>}><div className="signal"><div className="signal-line"><i className="dot red"/>HTTP 500</div><div className="arrow">↓</div><div className="signal-line"><i className="dot blue"/>payment.py</div><div className="arrow">↓</div><div className="signal-line"><i className="dot green"/>state guard</div></div><p className="muted">Evidence confidence: {run?.confidence||0}%</p></Panel><Panel title="EVIDENCE" icon={<GitBranch size={16}/>}><div className="big-number">{evidence.length}<small> artifacts</small></div><div className="evidence-mini">{evidence.slice(-3).map(x=><div key={x.id}><span>{x.kind}</span><b>{x.title}</b><em>{Math.round(x.confidence*100)}%</em></div>)}</div></Panel><Panel wide title="RELEASE GATE" icon={<UserCheck size={16}/>} >{waiting?<div className="approval"><div className="approval-head"><AlertTriangle size={22}/><div><b>Human approval required</b><span>NEXUS will not cross the production boundary automatically.</span></div></div><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Optional approval note..."/><div className="approval-actions"><button className="danger" onClick={()=>decide("reject")}><XCircle size={15}/>Reject</button><button className="approve" onClick={()=>decide("approve")}><CheckCircle2 size={15}/>Approve release</button></div></div>:<div className="gate-ok"><CheckCircle2/><div><b>{run?.status==="completed"?"Mission completed":"Gate armed"}</b><span>{run?.status==="completed"?"Human approval recorded. Staging deployment simulation passed.":"The evaluator will pause here if a production action requires authorization."}</span></div></div>}</Panel></div>}
function Timeline({events}){return <Panel title="AGENT TIMELINE" icon={<Activity size={16}/>}><div className="timeline">{events.map((e,i)=><motion.div initial={{opacity:0,x:-8}} animate={{opacity:1,x:0}} className="event" key={e.id||i}><div className="event-dot"/><div className="event-main"><div><b>{e.agent}</b><span>{e.action}</span></div><p>{e.detail}</p></div><em>{new Date(e.timestamp).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit",second:"2-digit"})}</em></motion.div>)}{!events.length&&<Empty text="No mission events yet."/>}</div></Panel>}
function Evidence({evidence}){return <div className="evidence-grid">{evidence.map(x=><motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="e-card" key={x.id}><div className="e-type">{x.kind}</div><h3>{x.title}</h3><p>{x.detail}</p><footer><span>{x.source}</span><b>{Math.round(x.confidence*100)}%</b></footer></motion.div>)}{!evidence.length&&<Empty text="Evidence will appear as agents inspect the system."/>}</div>}
function Diff({run}){return <Panel title="SANDBOX CODE DIFF" icon={<GitBranch size={16}/>}><div className="diff-meta"><span>checkout/payment.py</span><span>+3 / −2</span></div><pre className="diff"><code>{run?.diff||"// No patch generated yet."}</code></pre></Panel>}
function Security({run}){const rows=run?.security||[];return <div className="grid security-grid"><Panel title="POLICY FIREWALL" icon={<Shield size={16}/>}><div className="policy-list"><div><span>READ REPOSITORY</span><b className="allow">ALLOW</b></div><div><span>WRITE SANDBOX</span><b className="allow">ALLOW</b></div><div><span>CREATE PR</span><b className="logged">ALLOW + LOG</b></div><div><span>DEPLOY PRODUCTION</span><b className="review">HUMAN REVIEW</b></div><div><span>DELETE DATABASE</span><b className="block">BLOCK</b></div></div></Panel><Panel title="SECURITY SCAN" icon={<LockKeyhole size={16}/>}><div className="scan">{rows.length?rows.map((r,i)=><div key={i}><span>{r.severity}</span><b>{r.count}</b></div>):<Empty text="Run a mission to populate security findings."/>}</div></Panel></div>}
createRoot(document.getElementById("root")).render(<App/>);
