import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
await mkdir('artifacts/walkthrough',{recursive:true});
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:1280,height:800},recordVideo:{dir:'artifacts/walkthrough',size:{width:1280,height:800}},colorScheme:'dark',reducedMotion:'reduce'});
const started=Date.now();const page=await context.newPage();let verified=false;
function token(){const now=Math.floor(Date.now()/1000);return `${Buffer.from('{"alg":"none"}').toString('base64url')}.${Buffer.from(JSON.stringify({sub:'walkthrough-user',user_id:'walkthrough-user',aud:'nexyral',iss:'https://securetoken.google.com/nexyral',iat:now,exp:now+3600,email:'example@example.invalid',email_verified:verified,firebase:{sign_in_provider:'password'}})).toString('base64url')}.example`;}
const project={id:'33333333-3333-4333-8333-333333333333',intent:'Build a responsive support inbox with ticket search, filters and a clean team interface.',status:'draft',source:null as null|{app:string;css:string}};
await page.route('**/identitytoolkit.googleapis.com/**',async route=>{const url=route.request().url();await route.fulfill({json:url.includes('accounts:lookup')?{users:[{localId:'walkthrough-user',email:'example@example.invalid',emailVerified:verified,providerUserInfo:[{providerId:'password',email:'example@example.invalid'}]}]}:{localId:'walkthrough-user',email:'example@example.invalid',idToken:token(),refreshToken:'example-refresh',expiresIn:'3600',registered:true}});});
await page.route('**/securetoken.googleapis.com/**',route=>route.fulfill({json:{access_token:token(),id_token:token(),refresh_token:'example-refresh',expires_in:'3600',user_id:'walkthrough-user',project_id:'nexyral',token_type:'Bearer'}}));
await page.route('**/api/cloud/**',async route=>{const url=new URL(route.request().url());if(url.pathname.includes('/verification/')){if(url.pathname.endsWith('/confirm'))verified=true;await route.fulfill({json:{verified,sent:true}});return;}if(url.pathname.endsWith('/generate')){project.status='generated';project.source={app:'import { useState } from "react";\n\nexport default function App() {\n  const [query, setQuery] = useState("");\n  const tickets = ["Account access", "Billing question", "Team invitation"];\n  return <main>\n    <h1>Support inbox</h1>\n    <label>Find a ticket\n      <input value={query} onChange={event => setQuery(event.target.value)} />\n    </label>\n    <ul>{tickets.filter(ticket => ticket.toLowerCase().includes(query.toLowerCase()))\n      .map(ticket => <li key={ticket}>{ticket}</li>)}</ul>\n  </main>;\n}',css:'main { max-width: 960px; margin: auto; padding: 32px; }\ninput { width: 100%; padding: 14px; }'};await route.fulfill({json:{source:project.source,verification:'not_run'}});return;}await route.fulfill({status:url.pathname.endsWith('/projects')&&route.request().method()==='POST'?201:200,json:url.pathname.endsWith('/projects')?(route.request().method()==='POST'?{id:project.id}:{projects:[]}):project});});
await page.goto('http://127.0.0.1:4182/get-started');await page.getByRole('button',{name:'Create account',exact:true}).waitFor();await page.evaluate(async()=>await document.fonts.ready);
await page.evaluate(()=>{const banner=document.createElement('div');banner.id='walkthrough-caption';banner.style.cssText='position:fixed;bottom:0;left:0;right:0;z-index:1000;padding:20px 36px;background:#14131cee;border-top:1px solid #393347;backdrop-filter:blur(15px);color:#f4f1ff;font:500 24px Manrope,Arial;display:flex;justify-content:space-between;gap:24px;align-items:center';banner.innerHTML='<span id="walkthrough-step"></span><small style="font-size:13px;letter-spacing:.04em;color:#b3afc4">RECORDED WALKTHROUGH<br>EXAMPLE ACCOUNT & OUTPUT</small>';document.body.append(banner);});
async function caption(value:string){await page.locator('#walkthrough-step').evaluate((element,text)=>{element.textContent=text;},value);}
const ready=Date.now();const offset=(ready-started)/1000;
async function holdUntil(seconds:number){const remaining=ready+seconds*1000-Date.now();if(remaining>0)await new Promise(resolve=>setTimeout(resolve,remaining));}
try{
await caption('01 / Create your NEXYRAL account');await page.screenshot({path:'artifacts/walkthrough/poster.png'});await holdUntil(5);
await page.locator('input[name=email]').fill('example@example.invalid');await page.locator('input[name=password]').fill('example-password-123');await page.getByRole('button',{name:'Create account',exact:true}).click();await page.getByLabel('Six-digit email code').waitFor();await caption('02 / Enter the six-digit code from your email');await page.getByLabel('Six-digit email code').fill('123456');await holdUntil(10);
await page.getByRole('button',{name:'Verify email',exact:true}).click();await page.getByRole('button',{name:'Generate with Gemini'}).count();await caption('03 / Describe the pages, behavior and style');await page.getByLabel('What should we build?').pressSequentially(project.intent,{delay:20});await holdUntil(15);
await page.getByRole('button',{name:'Save project'}).click();await page.getByRole('button',{name:'Generate with Gemini'}).waitFor();await caption('04 / Save your idea to your workspace');await holdUntil(20);
await page.getByRole('button',{name:'Generate with Gemini'}).click();await page.getByRole('button',{name:'Download project',exact:true}).waitFor();await caption('05 / Generate source · response times vary');await holdUntil(25);
await page.getByRole('button',{name:'Download project',exact:true}).scrollIntoViewIfNeeded();await caption('06 / Download, review, then build and test locally');await holdUntil(30.3);
const video=page.video();await context.close();const path=await video!.path();
execFileSync('ffmpeg',['-y','-hide_banner','-loglevel','error','-ss',String(offset),'-i',path,'-frames:v','720','-vf','fps=24,tpad=stop_mode=clone:stop_duration=2','-c:v','libx264','-preset','fast','-crf','24','-pix_fmt','yuv420p','-an','-movflags','+faststart','public/media/nexyral-how-to-build.mp4']);
execFileSync('ffmpeg',['-y','-hide_banner','-loglevel','error','-i','artifacts/walkthrough/poster.png','-q:v','3','public/media/nexyral-walkthrough-poster.jpg']);
console.log(execFileSync('ffprobe',['-v','error','-show_entries','format=duration,size','-of','json','public/media/nexyral-how-to-build.mp4'],{encoding:'utf8'}));
}finally{await context.close();await browser.close();}
