export interface ProjectSource { app: string; css: string }
function crc32(bytes: Uint8Array): number {
  let crc = 0xffffffff;
  for (const byte of bytes) {
    crc ^= byte;
    for (let bit = 0; bit < 8; bit++) crc = (crc >>> 1) ^ (0xedb88320 & -(crc & 1));
  }
  return (crc ^ 0xffffffff) >>> 0;
}
function header(length: number) {
  const bytes = new Uint8Array(length);
  const view = new DataView(bytes.buffer);
  return { bytes, u16: (offset: number, value: number) => view.setUint16(offset, value, true), u32: (offset: number, value: number) => view.setUint32(offset, value, true) };
}
export function projectFiles(source: ProjectSource): Record<string, string> {
  return {
    'src/App.tsx': source.app,
    'src/styles.css': source.css,
    'src/vite-env.d.ts': '/// <reference types="vite/client" />\n',
    'src/main.tsx': 'import React from "react";\nimport { createRoot } from "react-dom/client";\nimport App from "./App";\nimport "./styles.css";\ncreateRoot(document.getElementById("root")!).render(<React.StrictMode><App /></React.StrictMode>);\n',
    'index.html': '<!doctype html>\n<html lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><title>NEXYRAL project</title></head><body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body></html>\n',
    'package.json': JSON.stringify({ name: 'nexyral-generated-project', version: '0.1.0', private: true, type: 'module', scripts: { dev: 'vite', build: 'tsc --noEmit && vite build', preview: 'vite preview' }, dependencies: { react: '19.2.8', 'react-dom': '19.2.8' }, devDependencies: { vite: '8.3.3', typescript: '6.0.2', '@types/react': '19.2.18', '@types/react-dom': '19.2.7', '@vitejs/plugin-react': '6.1.1' }, engines: { node: '>=24.19.0' } }, null, 2),
    'vite.config.ts': 'import { defineConfig } from "vite";\nimport react from "@vitejs/plugin-react";\nexport default defineConfig({ plugins: [react()] });\n',
    'tsconfig.json': JSON.stringify({ compilerOptions: { target: 'ES2023', lib: ['ES2023', 'DOM'], module: 'ESNext', moduleResolution: 'Bundler', jsx: 'react-jsx', strict: true, skipLibCheck: true, noEmit: true }, include: ['src'] }, null, 2),
    '.gitignore': 'node_modules/\ndist/\n.env*\n',
    'README.md': '# Generated with NEXYRAL\n\nThis frontend was generated by AI. Build, tests and deployment have not run. Review the source before execution. No backend, credentials or real authentication service is included.\n\nUse Node 24.19 or newer. In an isolated development directory:\n\n```sh\nnpm install\nnpm run build\nnpm run dev\n```\n\nA successful local build is separate from accessibility, security and behavior verification.\n',
  };
}
/** Uncompressed ZIP, fixed filenames only: no user-controlled paths or dependencies. */
export function exportProject(source: ProjectSource): Blob {
  const encode = new TextEncoder();
  const local: Uint8Array<ArrayBuffer>[] = [], central: Uint8Array<ArrayBuffer>[] = [];
  let offset = 0;
  const files = Object.entries(projectFiles(source));
  for (const [path, text] of files) {
    const name = encode.encode(path), data = encode.encode(text), crc = crc32(data);
    const item = header(30); item.u32(0, 0x04034b50); item.u16(4, 20); item.u16(6, 0x0800); item.u16(12, 0x0021); item.u32(14, crc); item.u32(18, data.length); item.u32(22, data.length); item.u16(26, name.length);
    local.push(item.bytes, name, data);
    const directory = header(46); directory.u32(0, 0x02014b50); directory.u16(4, 20); directory.u16(6, 20); directory.u16(8, 0x0800); directory.u16(14, 0x0021); directory.u32(16, crc); directory.u32(20, data.length); directory.u32(24, data.length); directory.u16(28, name.length); directory.u32(42, offset);
    central.push(directory.bytes, name); offset += item.bytes.length + name.length + data.length;
  }
  const centralSize = central.reduce((sum, item) => sum + item.length, 0);
  const end = header(22); end.u32(0, 0x06054b50); end.u16(8, files.length); end.u16(10, files.length); end.u32(12, centralSize); end.u32(16, offset);
  return new Blob([...local, ...central, end.bytes], { type: 'application/zip' });
}
